[project]
name = "piazan"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apscheduler>=3.11.0",
    "gpiozero>=2.0.1",
    "pydub>=0.25.1",
    "pytz>=2025.2",
    "simpleaudio>=1.0.4",
    "timezonefinder>=6.5.9",
]
